import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import QueryProvider from "@/components/providers/query-provider";
import { RealTimeNotifications } from "@/components/real-time-notifications";

export const metadata: Metadata = {
  title: "Full Stack Template",
  description: "Generated by GitHub Copilot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans antialiased">
        <QueryProvider>
          <RealTimeNotifications />
          {children}
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
